version: "3.9"
services:
  api:
    build:
      context: ../specification-pattern-movies-api/
      dockerfile: ./MoviesApi/Dockerfile
    container_name: specification-pattern-movies-api
    volumes:
      - "../specification-pattern-movies-api/MoviesApi/.:/source"
    env_file:
      - ../specification-pattern-movies-api/MoviesApi/.env
    ports:
      - "0.0.0.0:8080:80"
    expose:
      - "80"
  webapp:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: "specification-pattern-movies-webapp"
    ports:
      - "0.0.0.0:8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - "8000"
    depends_on: 
        - api
    links: 
        - api
    tty: true