apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-08T02:24:48Z"
  labels:
    app: specification-pattern-movies-webapp
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-06-08T02:24:48Z"
  name: specification-pattern-movies-webapp-service
  namespace: default
  resourceVersion: "13066"
  selfLink: /api/v1/namespaces/default/services/specification-pattern-movies-webapp-service
  uid: 817f2607-6367-4237-b34c-25fa54c4901f
spec:
  clusterIP: 10.98.120.246
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31464
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: specification-pattern-movies-webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
